baseurl = "https://fcumselab.github.io/ProgEdu/"
languageCode = "en-us"
publishDir = "../docs"
title = "ProgEdu"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
uglyurls = true
disableKinds = ["taxonomy", "taxonomyTerm"]

# Enable Google Analytics by entering your tracking id
# googleAnalytics = "UA-37514928-9"

[params]
	# General information
	author = "FCU MSELab"
	description = "changeme"
	copyright = ""

	# Repository
	provider = ""
	repo_url = ""

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["custom-style.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-purple"
    	accent  = "purple"

    [params.font]
    	text = "Doctarine"
    	code = "Source Code Pro"

[social]
	twitter = ""
	github  = "fcumselab/ProgEdu"
	email   = ""

# ------- MENU START -----------------------------------------

[[menu.main]]
	name   = "1. Introduction"
	url    = "introduction/"
	weight = 1

[[menu.main]]
	name   = "2. Getting Started"
	url    = "getting-started/"
	weight = 2

[[menu.main]]
	name   = "3. Documentation"
	url    = "documentation/"
	weight = 3

[[menu.main]]
	name   = "4. Guides"
	url    = "guides/"
	weight = 4

[[menu.main]]
	name   = "5. Help & Questions"
	url    = "help/"
	weight = 5

[[menu.main]]
	name   = "6. Related Projects"
	url    = "related-projects/"
	weight = 6

[[menu.main]]
	name   = "7. Contributing"
	url    = "contributing/"
	weight = 7

[[menu.main]]
	name   = "8. License"
	url    = "license/"
	weight = 8

# ------- MENU END -----------------------------------------

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

